"""models iniftdsad

Revision ID: 0af56fb04dd8
Revises: f055f8ee060f
Create Date: 2023-05-11 22:36:48.192640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af56fb04dd8'
down_revision = 'f055f8ee060f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
