"""sad

Revision ID: 1b1c90b80bfe
Revises: 0af56fb04dd8
Create Date: 2023-05-12 14:57:35.618417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1c90b80bfe'
down_revision = '0af56fb04dd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
