"""sad

Revision ID: 2fe10df12450
Revises: f995ec4ae746
Create Date: 2023-05-12 15:19:31.399193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe10df12450'
down_revision = 'f995ec4ae746'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['Category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['color_id'], ['Color.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Theme')
    # ### end Alembic commands ###
