"""timezone

Revision ID: 65db1e4f4b63
Revises: f37c85133e3f
Create Date: 2023-05-16 16:30:09.124222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65db1e4f4b63'
down_revision = 'f37c85133e3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Task', sa.Column('date_created_timezone', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Task', 'date_created_timezone')
    # ### end Alembic commands ###
