"""slug is not nullable

Revision ID: 72dab37cd6e7
Revises: e16e40a29ddd
Create Date: 2023-05-16 21:47:00.900073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72dab37cd6e7'
down_revision = 'e16e40a29ddd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Category', 'slug',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('Theme', 'slug',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Theme', 'slug',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('Category', 'slug',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
