"""slug

Revision ID: d0c5356ca5f4
Revises: 0a0a0a0350e1
Create Date: 2023-05-15 17:31:47.919567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c5356ca5f4'
down_revision = '0a0a0a0350e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Category', sa.Column('slug', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'Category', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Category', type_='unique')
    op.drop_column('Category', 'slug')
    # ### end Alembic commands ###
