"""field color for user is added

Revision ID: e17950d3b69c
Revises: e63935157122
Create Date: 2023-06-05 12:09:13.265287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17950d3b69c'
down_revision = 'e63935157122'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('color_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'User', 'Color', ['color_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.drop_column('User', 'color_id')
    # ### end Alembic commands ###
