"""slug

Revision ID: f37c85133e3f
Revises: d0c5356ca5f4
Create Date: 2023-05-15 17:32:48.698516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37c85133e3f'
down_revision = 'd0c5356ca5f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Task', sa.Column('slug', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'Task', ['slug'])
    op.add_column('Theme', sa.Column('slug', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'Theme', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Theme', type_='unique')
    op.drop_column('Theme', 'slug')
    op.drop_constraint(None, 'Task', type_='unique')
    op.drop_column('Task', 'slug')
    # ### end Alembic commands ###
