"""sad

Revision ID: f995ec4ae746
Revises: 8c505f9edbc8
Create Date: 2023-05-12 15:16:34.322441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f995ec4ae746'
down_revision = '8c505f9edbc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
